# Generated by Django 5.1.5 on 2025-03-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_author', models.CharField(default='user', max_length=255)),
                ('street_address', models.TextField(default='Nigeria')),
                ('city', models.CharField(default='', max_length=255)),
                ('state', models.CharField(default=' ', max_length=255)),
                ('LGA', models.CharField(default=' ', max_length=255)),
                ('postal_code', models.IntegerField(default=100001)),
                ('event_description', models.TextField(default='owanbe')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('delivery_address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_image', models.TextField(null=True)),
                ('reconciliation', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
