# Generated by Django 5.1.5 on 2025-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='currency_image',
        ),
        migrations.AddField(
            model_name='events',
            name='currency_image_100',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='currency_image_1000',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='currency_image_200',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='currency_image_50',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='currency_image_500',
            field=models.TextField(null=True),
        ),
    ]
