# Generated by Django 5.1.7 on 2025-03-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_currency_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='currency_image_100',
        ),
        migrations.RemoveField(
            model_name='events',
            name='currency_image_1000',
        ),
        migrations.RemoveField(
            model_name='events',
            name='currency_image_200',
        ),
        migrations.RemoveField(
            model_name='events',
            name='currency_image_50',
        ),
        migrations.RemoveField(
            model_name='events',
            name='currency_image_500',
        ),
        migrations.AddField(
            model_name='events',
            name='currency_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
