# Generated by Django 5.1.7 on 2025-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_has_reserved_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='payment_status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
    ]
