# Generated by Django 5.1.7 on 2025-05-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_events_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='delivery_status',
            field=models.CharField(choices=[('pending payment', 'pending payment'), ('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending payment', max_length=50),
        ),
    ]
