# Generated by Django 5.1.5 on 2025-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('event_author', models.CharField(default='user', max_length=255)),
                ('event_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_name', models.CharField(default='Party Currency', max_length=255)),
                ('front_celebration_text', models.CharField(default='Party Currency', max_length=255)),
                ('front_image', models.TextField(null=True)),
                ('back_image', models.TextField(null=True)),
                ('back_celebration_text', models.CharField(default='Party Currency', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
