# Generated by Django 5.1.7 on 2025-05-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_remove_currency_event_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='denomination',
            field=models.IntegerField(choices=[(1000, '1000'), (500, '500'), (200, '200'), (100, '100')], null=True),
        ),
    ]
