# Generated by Django 5.1.5 on 2025-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
