# Generated by Django 5.1.7 on 2025-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_total_amount_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='virtual_account_reference',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
