# Generated by Django 5.1.5 on 2025-02-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='redirect_url',
        ),
        migrations.AddField(
            model_name='transaction',
            name='event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
