# Generated by Django 5.1.5 on 2025-02-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_transaction_redirect_url_transaction_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contract_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
