# Generated by Django 5.1.5 on 2025-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_contract_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='redirect_url',
            field=models.URLField(blank=True),
        ),
    ]
