# Generated by Django 5.1.7 on 2025-05-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
