# Generated by Django 5.1.7 on 2025-05-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='breakdown',
            field=models.CharField(default='', max_length=555),
        ),
    ]
